### ISSUE TITLE
properties格式配置文件高亮支持

### ISSUE THREAD

**Issue by VVFtang** [polarismesh/polaris-console#118]
![image](https://user-images.githubusercontent.com/105641045/191914260-26abed97-b095-4a81-b315-62abefb4f2a8.png)

**Comment by chuntaojun** [comment]
ok，we will support it

**Comment by yidafu** [comment]
@chuntaojun 我来该？

**Comment by chuntaojun** [comment]
> @chuntaojun 我来改？

那应该需要支持 properties、yaml、yml、json、xml 这几个常见的
