### ISSUE TITLE
限流规则页面支持点击规则ID进入查询页面

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-console#121]
![Screen Shot 2022-09-29 at 10 07 08](https://user-images.githubusercontent.com/23445172/192922274-42ad0056-a6d2-4005-a432-c247f16802bd.png)

要求

- 可以点击规则id进入规则详细页面
- 该页面只能查看规则，不得对规则进行编辑

**Comment by iLunZ** [comment]
接
