### ISSUE TITLE
配置文件编辑时，需要支持语法检查

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-console#152]
暂时先支持一下几种

- yaml/yml
- json
- properties
- xml

**Comment by yidafu** [comment]
json/xml 使用语法检查的

### xml

![image](https://user-images.githubusercontent.com/22773923/207380147-a19346eb-6555-47c6-9394-a210ff2975e0.png)

### json
![image](https://user-images.githubusercontent.com/22773923/207380379-ab0cfd79-b758-4821-b6d5-064066cca269.png)

**Comment by chuntaojun** [comment]
我觉得可以

**Comment by yidafu** [comment]
`yaml/yml`和`properties`格式需要额外支持语法检查，我来搞一下吧。

**Comment by yidafu** [comment]
实现效果：

![image](https://user-images.githubusercontent.com/22773923/208457569-835d62e9-3a12-4407-8af0-cc61ba62f72e.png)

![image](https://user-images.githubusercontent.com/22773923/208457725-5897808d-307f-48ca-8694-d49a76ffecc0.png)
