### ISSUE TITLE
配置中心支持配置分组粒度的配置导入导出交互

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-console#197]
配置支持按命名空间选择「全部配置分组」「某些配置分组」导入、导出。

文件格式：zip

格式：命名空间名称/配置分组/配置

导入时，需要用户选择遇到同名文件/文件夹是覆盖还是跳过。

一次导入一个zip包

![image](https://user-images.githubusercontent.com/23445172/224920216-333baa8b-1f83-495f-87a2-96674bf6ba37.png)

![image](https://user-images.githubusercontent.com/23445172/224920294-b98edffe-2b0a-4ab7-801e-5761c7ba0886.png)

![image](https://user-images.githubusercontent.com/23445172/224920323-d2fdd931-30d8-495a-ab50-b26d47754556.png)

导入过程：
![image](https://user-images.githubusercontent.com/23445172/224920377-c65b2431-a543-4871-9872-c8c41a052818.png)
导入成功：
![image](https://user-images.githubusercontent.com/23445172/224920398-a61559c9-a6a9-4b57-a851-4797dc36aa4a.png)
导入失败：
![image](https://user-images.githubusercontent.com/23445172/224920429-3d489e89-dad0-44df-8056-e60159370929.png)

**Comment by yidafu** [comment]
@chuntaojun 接口文档有吗

**Comment by chuntaojun** [comment]
> @chuntaojun 接口文档有吗

有的

**Comment by alexwanglei** [comment]
# 配置文件导入
## POST /config/v1/configfiles/import
## 请求参数
|  参数   |  类型  | 传参形式 | 是否必须 | 描述 | 
|  ----  | ----  | ---- |  ----  | ----  |
| namespace  | string | form | 是 | 命名空间 |
| group  | string | form | 否 | 配置分组 |
| conflict_handling | string | form  | 是 | 配置文件冲突处理，跳过skip，覆盖overwrite |
| config | zip文件 | form | 是 | 配置文件 |

鉴权header ：X-Polaris-Token: {访问凭据}

## 响应结果 
|  参数   |  类型   | 描述 | 
|  ----  | ----  | ---- | 
| code  | int  | 响应码|
| info  | string | 响应信息 |
| createConfigFiles | ConfigFile数组 | 创建的配置文件 |
| skipConfigFiles | ConfigFile数组 | 跳过的配置文件 |
| overwriteConfigFiles | ConfigFile数组 | 覆盖的配置文件 |

## 例子
```shell
curl -v -XPOST \    
-H'X-Polaris-Token:nu/0WRA4EqSR1FagrjRj0fZwPXuGlMpX+zCuWu4uMqy8xr1vRjisSbA25aAC3mtU8MeeRsKhQiDAynUR09I=' \
--form 'namespace="import"' \
--form 'conflict_handling="skip"' \
--form 'config=@"import_group_c.zip"' \
http://127.0.0.1:8090/config/v1/configfiles/import
```
```json
{
 "code": 200000,
 "info": "execute success",
 "createConfigFiles": [
  {
   "id": "64",
   "name": "c.txt",
   "namespace": "import",
   "group": "group_c",
   "content": "123\n",
   "format": "txt",
   "comment": "测试c",
   "status": null,
   "tags": [
   ],
   "createTime": "2023-03-20 10:30:14",
   "createBy": "polaris",
   "modifyTime": "2023-03-20 10:30:14",
   "modifyBy": "",
   "releaseTime": null,
   "releaseBy": null,
   "encrypt": null
  }
 ],
 "skipConfigFiles": [
  {
   "id": null,
   "name": "a.yml",
   "namespace": "import",
   "group": "group_c",
   "content": "name: \"hello world\"\n",
   "format": "yml",
   "comment": null,
   "status": null,
   "tags": [
   ],
   "createTime": null,
   "createBy": "polaris",
   "modifyTime": null,
   "modifyBy": "polaris",
   "releaseTime": null,
   "releaseBy": null,
   "encrypt": null
  },
  {
   "id": null,
   "name": "b.txt",
   "namespace": "import",
   "group": "group_c",
   "content": "123\n",
   "format": "txt",
   "comment": "测试",
   "status": null,
   "tags": [
    {
     "key": "k1",
     "value": "v1"
    },
    {
     "key": "k2",
     "value": "v2"
    }
   ],
   "createTime": null,
   "createBy": "polaris",
   "modifyTime": null,
   "modifyBy": "polaris",
   "releaseTime": null,
   "releaseBy": null,
   "encrypt": null
  },
  {
   "id": null,
   "name": "white_list.json",
   "namespace": "import",
   "group": "group_c",
   "content": "{\n    \"test\": 100\n}\n",
   "format": "json",
   "comment": "白名单",
   "status": null,
   "tags": [
    {
     "key": "b",
     "value": "banana"
    }
   ],
   "createTime": null,
   "createBy": "polaris",
   "modifyTime": null,
   "modifyBy": "polaris",
   "releaseTime": null,
   "releaseBy": null,
   "encrypt": null
  }
 ],
 "overwriteConfigFiles": [
 ]
}
```

**Comment by alexwanglei** [comment]
# 配置文件导出
## POST /config/v1/configfiles/export
## 请求参数
|  参数   |  类型  | 传参形式 | 描述 |
|  ----  | ----  | ---- |  ----  |
| namespace  | string | json | 导出的命名空间 |
| groups  | string数组 | json |  导出的配置分组 |
| names | string数组 |  json | 导出的配置文件 |

## 响应结果 
### 导出成功
返回文件流 Content-Type = "application/zip"，"attachment; filename=config.zip"
### 导出失败
返回 json
|  参数   |  类型   | 描述 | 
|  ----  | ----  | ---- | 
| code  | int  | 错误码|
| info  | string | 错误信息 |

## 例子
```shell
curl -v -XPOST -H'Content-Type:application/json' -d'{                                                      
"namespace": "import",
"groups": [
"group_c"
],
"names": [
"white_list.json",
"a.yml"
]
}' http://127.0.0.1:8090/config/v1/configfiles/export -o export2.zip
```

**Comment by chuntaojun** [comment]
> @chuntaojun 接口文档有吗

已经在评论了回复了，大佬这里有时间搞？

**Comment by yidafu** [comment]
@chuntaojun

![image](https://user-images.githubusercontent.com/22773923/228895882-df6063d6-3a1a-491e-9253-90af7505d915.png)
这个上传没有必要吧？接口是直接上传 zip 包，不是先上传云存储得到 url 再请求导出接口

![image](https://user-images.githubusercontent.com/22773923/228896997-9c1ca841-af84-4952-afdd-6aa6f157228e.png)


没有导入中的状态呀，这里的进度条没有必要？没有接口去轮询导入状态，请求结束后直接就返回了结果

**Comment by chuntaojun** [comment]
1、没有必要了

**Comment by yidafu** [comment]
报错 `request decode failed: invalid config file`

上传的文件是导出来的

![image](https://user-images.githubusercontent.com/22773923/229357371-d65a5c17-5ffc-4d0e-a260-9acb17d174b2.png)

解压结果

![image](https://user-images.githubusercontent.com/22773923/229357469-c8d3da86-dfa0-4dfc-8194-4abdcc85a725.png)

@alexwanglei

**Comment by alexwanglei** [comment]
看一下错误日志里面打印的什么？把这个zip包发给我试一下
