### ISSUE TITLE
限流页面显示异常

### ISSUE THREAD

**Issue by wgfxcu** [polarismesh/polaris-console#24]
单机版本polaris-console-release_v1.2.1.linux.amd64，连接mysql。限流规则页面显示异常，如下图:
![bee9459b0777c01adddf766c9664321](https://user-images.githubusercontent.com/24292252/142566826-cf33744c-cb28-41f7-aa99-d5b9e307f8df.png)

使用curl添加限流规则后再访问页面，显示异常，如下图:
![a042c8b0018ff296e71a4a198d9cff2](https://user-images.githubusercontent.com/24292252/142566848-4ecb83e1-b57e-4298-ba82-9260995486cf.png)

**Comment by chuntaojun** [comment]
we will follow

**Comment by chuntaojun** [comment]
第一个问题，下个版本会进行修复显示不友好的问题

**Comment by chuntaojun** [comment]
already fix
