### ISSUE TITLE
能否考虑在控制台添加一个polaris mesh的官网链接？

### ISSUE THREAD

**Issue by li-xiao-shuang** [polarismesh/polaris-console#27]
![image](https://user-images.githubusercontent.com/34903552/144556097-668daf9d-2858-4881-9db1-52d8d633e772.png)

添加一个跳转链接 在使用控制台的时候有需要看文档 就可以直接跳转了 使用起来更方便一些，或者点击图标跳转也行
![image](https://user-images.githubusercontent.com/34903552/144556398-3bdf21b6-e3ad-4b19-aaa1-0d44809ade8d.png)

**Comment by chuntaojun** [comment]
I think it's good idea
