### ISSUE TITLE
下载v1.5.6 查看里面显示v1.5.3 没有变化，是不是打包没有更新哦？

### ISSUE THREAD

**Issue by apoyl** [polarismesh/polaris-console#48]
下载v1.5.6 查看里面显示v1.5.3 没有变化，是不是打包没有更新哦？
![image](https://user-images.githubusercontent.com/1912452/163304350-98b12886-79ff-494d-ba21-e6868b1c9eed.png)

**Comment by chuntaojun** [comment]
这里我们调整下打包脚本的问题，里面的程序是最新的，打包名称这里的问题我们修复下

**Comment by chuntaojun** [comment]
已经修复
