### ISSUE TITLE
安装报错： error   handlers/hrData.go:68   read department.txt err: open department.txt: no such file or directory

### ISSUE THREAD

**Issue by apoyl** [polarismesh/polaris-console#49]
polaris-server  安装正常 polaris-console安装报错： error   handlers/hrData.go:68   read department.txt err: open department.txt: no such file or directory
![image](https://user-images.githubusercontent.com/1912452/163305447-a4b5fcd5-69ce-4c52-941e-afa354ef09ff.png)

**Comment by chuntaojun** [comment]
这个错误并不会影响正常的流程，可以忽略。我们这里优化下

**Comment by apoyl** [comment]
可以看截图启动了polaris-console  但是进程里里没有polaris-console 服务哦，启动不了

**Comment by Albertchamberlain** [comment]
> 可以看截图启动了polaris-console 但是进程里里没有polaris-console 服务哦，启动不了

![image](https://user-images.githubusercontent.com/47343901/167536238-1548f90f-ace5-4371-b4c0-6aeb85d5a049.png)
