### ISSUE TITLE
[WIP] 移除 handlers/hrData.go 相关逻辑

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-console#50]
issue #49

**Comment by chuntaojun** [comment]
welcome contribute

**Comment by Albertchamberlain** [comment]
hi , 这是否意味着直接移除handlers/hr_data.go 中 第61-64行错误处理逻辑即可 
https://github.com/polarismesh/polaris-console/blob/5f816edc1d5d920b4aba00f2919ad94d73bf6cb5/handlers/hr_data.go#L61

**Comment by chuntaojun** [comment]
这里应该是hr_data中相关的逻辑都可以不需要了
