### ISSUE TITLE
增加文件发布状态提示,增加文件后缀提示

### ISSUE THREAD

**Issue by vinartis** [polarismesh/polaris-console#59]
**What is the feature you want to add?**
![1655271269813](https://user-images.githubusercontent.com/4651907/173748490-217bc0a2-0a2b-474e-acaa-6b09aaa9bf67.jpg)
![1655271355266](https://user-images.githubusercontent.com/4651907/173748561-7687a944-6ccc-4631-8b14-cea3a1355ce9.jpg)

**Why do you want to add this feature?**
1 如果文件比较多时候，不容易分辨哪个文件还没有发布

2 我在第一次建立文件的时候，没有加入yml后缀名，格式选择的yaml，在应用中引入的时候，也没加入后缀名，这个时候，应用不能正确识别这个文件为yaml文件。后台在配置中心将文件名增加上后缀，引入的时候也加上后缀，才正确识别了。

**How to implement this feature?**
增加必要的提示信息

**Comment by chuntaojun** [comment]
i think it's good idea

**Comment by chuntaojun** [comment]
第二个问题，是指在使用 spring-cloud-tencent 的时候遇到的吗？

**Comment by vinartis** [comment]
> 第二个问题，是指在使用 spring-cloud-tencent 的时候遇到的吗？

是的，使用 spring-cloud-starter-tencent-polaris-config 的时候碰到的。

**Comment by lepdou** [comment]
@vinartis 
很好的建议，我们优化一下。感谢~
