### ISSUE TITLE
build.sh脚本缺失

### ISSUE THREAD

**Issue by 332947843** [polarismesh/polaris-console#63]
build.sh缺失以下脚本，导致无法build成功
set -e

if [[ $(uname) == 'Darwin' ]]; then
  realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
  }

  md5sum() {
    md5 $*
  }
fi

**Comment by chuntaojun** [comment]
ok，we will fix it
