### ISSUE TITLE
地理信息 展示与更新有问题

### ISSUE THREAD

**Issue by davionchen** [polarismesh/polaris-console#93]
问题描述：

以自动注册的方式，将服务注册到北极星。

1、通过控制台 查看实例信息，发现实例标签包含region/zone等信息。但是地域信息无内容，预期应该是有的。
![image](https://user-images.githubusercontent.com/2884774/185030528-949fdbb4-d23e-466b-97ac-d2ab69a729bf.png)

2、通过地域信息修改region/zone，结果无法同步到实例标签中。

**Comment by chuntaojun** [comment]
这里SCT侧进行修改
